### ISSUE TITLE
코드 구현 관련 질문

### ISSUE THREAD

**Issue by Alegruz** [Yeonwu/SoftBodyTetris#1]
안녕하세요,
소융 졸업생이라는 고대의 유물이 감히 후배님들 블로그 돌아보다가 주제가 흥미로워서 둘러보다가 몇 가지 질문이 있어 issue로 남겨봅니다 ^^

https://github.com/Yeonwu/SoftBodyTetris/blob/master/SoftBodyTetris/engine/physics/point/IPoint.hpp
여기서 position나 mass 같은 걸 전부 pure abstract 함수로 두시고 정작 masspoint나 fixedpoint나 둘 다 mass와 position가 있던데, 
굳이 공통화를 안 하신 이유가 있을까요?

**Comment by Yeonwu** [comment]
안녕하세요! 난잡한 코드를 직접 읽어보시고 코멘트까지 해주시다니 감사합니다. 조금 변명을 해보자면, 소융개론 텀프로 진행한 프로젝트인데 시뮬레이션 분야를 처음 개발해보아서 조금 더럽게 구현되었습니다. Verlet을 중간에 도입하게되어 이전에 사용하던 속도 관련 코드들이 그대로 남아있다던지 ㅎㅎ... 아무튼 제가 공통화를 하지 않은 이유는 다음과 같습니다.

IPoint 클래스를 설계할 때 나중에 추가적으로 다른 Point들이 필요하게 될지 모르고, 또 각 Point들이 질량과 위치를 어떻게 처리하게 될지 확실하지 않았습니다. 그래서 추상 함수로 선언하고, 굳이 MassPoint와 FixedPoint의 구현을 IPoint로 옮기지 않았습니다. 

예를 들어 각각의 setPotision 함수를 보시면, [MassPoint](https://github.com/Yeonwu/SoftBodyTetris/blob/3692433b154a7392a094a8530e30d04979afbd82/SoftBodyTetris/engine/physics/point/MassPoint.cpp#L32)는 위치 변경이 가능하기 때문에 구현이 되어있지만 [FixedPoint](https://github.com/Yeonwu/SoftBodyTetris/blob/3692433b154a7392a094a8530e30d04979afbd82/SoftBodyTetris/engine/physics/point/FixedPoint.cpp#L25)는 위치 변경이 불가능하므로 빈 함수가 들어있습니다. 굳이 FixedPoint에 setPosition 함수를 넣어둔 이유는 연산할 때 둘 다 IPoint* 배열에 저장하고 반복문으로 한번에 훑기 때문입니다. [(예시)](https://github.com/Yeonwu/SoftBodyTetris/blob/3692433b154a7392a094a8530e30d04979afbd82/SoftBodyTetris/engine/physics/body/SoftBody.cpp#L32) 마찬가지로 이외의 어떤 종류의 Point가 차후 추가되든 IPoint라는 통일된 인터페이스로 다루고 싶었기 때문에 이와 같이 만들었습니다.

저도 만들다보니 getPosition와 같이 중복되는 함수가 있어 이런 함수들을 IPoint로 옮길지 따로 둘지 고민을 했었습니다만, 그대로 두기로 결정한 이유는 IPoint는 인터페이스이므로 어떤 타입의 함수가 구현체에 있어야하는지 정의할 뿐 구현이 있어서는 안된다고 생각했기 때문입니다. 

주신 질문에 대해 답하다보니 IPoint에 기본적인 함수 구현을 넣고 다른 구현이 필요할 경우 그냥 override해서 사용하는 게 중복을 줄이는데 나을 것 같다는 생각이 드네요.

**Comment by Alegruz** [comment]
그럼 IPoint가 인터페이스가 아니면 되겠군요?

예시)

```cpp
class PointBase
{
public:
    float getMass() const { return mMass; }
    ...
protected:
    float mMass;
    ...
};
```

각 결정에 대해 한 번 질문/피드백을 들리자면, IPoint 클래스를 설계할 때 다른 Point들이 필요할지 모른다와 IPoint 자체적으로 position이 있는 거랑은 별개인 것 같습니다. IPoint 클래스라는 걸 인터페이스라는 점을 빼면, 사실 점이라는 논리적인 개념인데, 점이라는 건 수학적으로 당연히 위치가 있어야할 것 같거든요. 각 point가 질량과 위치를 어떻게 처리할지 확실하지는 않더라도, 적어도 위치라는 속성은 당연히 있지 않나 싶었습니다

**Comment by Yeonwu** [comment]
사고 과정에 대해 피드백해주셔서 감사합니다. 한가지 질문이 있는데, 이와 같이 모든 구현체가 같은 구현을 사용한다고 가정했을 때, 인터페이스에 간단한 구현을 넣는 게 바람직한가요? 아니면 인터페이스는 인터페이스대로 두고, 모든 구현체가 상속받을 구현체를 하나 만드는게 나을까요? 이 경우 나중에 다른 구현을 원하는 구현체도 유연하게 추가할 수 있고, 중복도 줄일 수 있을 것 같습니다.

```c++
class IPoint {
    public:
        virtual float getMass() const = 0;
};

class PointBase: public IPoint {
    private:
        float mMass;
    public:
        float getMass() const override {
            return mMass;
        }
};

class MassPoint: PointBase {
    ...
}

class FixedPoint: PointBase {
    ...
}

class AbsolutePoint: IPoint {
    public:
        float getMass() const override {
            return 10;
        }
}
```

속도를 예시로 들어 조금 더 부연 설명하자면, 제가 이 프로젝트를 시작하기 전 알고 있던 물리학에서 point는 속도를 가져야 합니다. 하지만 Verlet Integration을 사용하면 속도를 어떤 정해진 값으로 갖지 않고, 변위/timestep으로 나타내게 됩니다. 따라서 getVelocity, setVelocity 메서드는 [다음](https://github.com/Yeonwu/SoftBodyTetris/blob/3692433b154a7392a094a8530e30d04979afbd82/SoftBodyTetris/engine/physics/point/MassPoint.cpp#L41)과 같이 velocity라는 속성값을 사용하지 않고 position, oldPosition을 바탕으로 계산해서 속도를 다룹니다.

**Comment by Alegruz** [comment]
과도한 추상화가 아닌가 싶습니다

과도한 추상화로 생각해야 할 가짓수가 많아지면 나중에 코드를 읽었을 때 분석 및 유지보수하기가 어렵습니다

또한 MassPoint라는 클래스가 있는데 getMass가 IPoint에 있는 건 뭔가 자연스럽지 않은 듯 합니다

보통 이런 설계를 할 때는 IPoint를 먼저 생각하고 구현하는 것보다는 구체적인 것들을 각기 구현해보고 공통화를 하는 것이 더 낫습니다

보통 일반화/공통화/추상화는 가장 먼저하는 작업이 아닌 경우가 많습니다. 왜냐면 보통 저희는 처음 해보는 일은 "모르기 때문"에 일반화/공통화/추상화가 힘듭니다. 물론 이미 해본 일이고, 완벽하게 머릿속에 구조가 그려진다면 추상화가 쉬울 것입니다.

**Comment by Alegruz** [comment]
평생 혼자 1인 개발을 하더라도, 불과 주말 전의 나와 주말 이후의 나는 다른 사람입니다. 사람은 망각하기 마련이고, 그렇다고 문서화를 철저하게 하자니 개발 시간을 소비하게 됩니다
그렇기에 읽기 쉽도록, 머릿 속에 생각의 단계를 최소화할 수 있게 하는 방향으로 구조화/추상화를 하시면 됩니다.

**Comment by Yeonwu** [comment]
너무 추상화에 집착하지 말고 "읽기 쉬운 코드"를 짜야한다는 뜻으로 이해했습니다. 그러기 위해서는 우선 구체적으로 구현을 해본 다음 공통된 부분을 추려야하는군요. 추상화는 어디까지나 좋은 코드를 짜기 위한 도구일 뿐, 추상화 자체를 목적으로 코드를 짜면 오히려 분석 및 유지보수가 힘들어질 수 있다는 점 명심하겠습니다. 많이 배웠습니다. 감사합니다! 좋은 하루 되세요 :)
